package:
  name: my-package
  version: "0.1.0"

source:
  # Option 1: From PyPI
  # url: https://pypi.io/packages/source/m/my-package/my-package-{{ version }}.tar.gz
  # sha256: abc123...
  
  # Option 2: From GitHub
  # git_url: https://github.com/username/my-package.git
  # git_rev: v{{ version }}
  
  # Option 3: From local path (for development)
  path: ../

build:
  number: 0
  script: python -m pip install . -vv
  noarch: python
  
  # If you have console scripts/entry points
  entry_points:
    - my-command = my_package.main:main

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
    - pyyaml
  run:
    - python >=3.11
    - numpy >=1.20
    - pandas >=1.3
    # Add your runtime dependencies here

test:
  imports:
    - my_package
  commands:
    - my-command --help
  requires:
    - pytest
    - pytest-cov
    - anaconda-ident

about:
  home: https://github.com/username/my-package
  license: MIT
  license_file: LICENSE
  summary: A brief description of my package
  description: |
    A more detailed description of what my package does.
    This can span multiple lines.
  doc_url: https://my-package.readthedocs.io
  dev_url: https://github.com/username/my-package

extra:
  recipe-maintainers:
    - your-github-username
